### ISSUE TITLE
X-SAMPA, '`@' not rendering as 'ɚ'

### ISSUE THREAD

**Issue by John-Toohey** [imatpot/typst-packages#1] opened 2023-12-11 20:01 UTC
Given the input ``E@`pO@`t``, I would expect the output /ɛɚpɔɚt/, but alas no.  Rather the output generated is   
![image](https://github.com/imatpot/typst-packages/assets/21034889/fca9ebce-8bee-4a1c-9ab8-074094a8fcd0)  
which is quite jarring.  I believe this is due to the diacritics being replaced before the `` @` `` in the xsampa translations.

**Comment by imatpot** [comment] 2023-12-26 21:40
Thank you for reporting the issue! You are correct, this is caused by ``` ` ``` being replaced before I check for ``` @` ```.

I have fixed the issue and added ``` ("E@`p0@`t", "ɛɚpɔɚt") ``` as a test case as well. It will be fixed with the release of 1.1.1 (https://github.com/typst/packages/pull/312)

**Closed by imatpot** 2023-12-26 21:40 UTC
